### ISSUE TITLE
ERROR - new ele module missing

### ISSUE THREAD

**Issue by MDallOsso** [CMS-PD/ALPHA#141]
We implemented changes for Ele/Mu SF in HH analyzer but an ele_id_modules is missing
(**cutBasedElectronID_Summer16_80X_V1_cff**).
The same happens if we run Diboson.py:

> -bash-4.1$ python python/Diboson.py  
> Running on MC , sample is 
> -> re-HLT sample
> Conditions read from  CMS_CONDITIONS  via FrontierProd 
> Traceback (most recent call last):
>   File "python/Diboson.py", line 171, in <module>
>     setupAllVIDIdsInModule(process,ele_idmod,setupVIDElectronSelection)
>   File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_12/python/PhysicsTools/SelectorUtils/tools/vid_id_tools.py", line 52, in setupAllVIDIdsInModule
>     idmod= **import**(id_module_name, globals(), locals(), ['idName','cutFlow'])
> ImportError: No module named cutBasedElectronID_Summer16_80X_V1_cff

It should be in cmssw_8_0_12.
Temporary Patch -> we go back to previous modules.

Martino

**Comment by jpazzini** [comment]
This should be easily solved by merging the latest developements from EGamma
`git cms-merge-topic -u ikrav:egm_id_80X_v1` 
as reported in the PR description https://github.com/CMS-PD/ALPHA/pull/138

Will update the README file and Twiki accordingly

**Comment by MDallOsso** [comment]
Okay. I missed the PR description, sorry.
Command added to the twiki too.
