### ISSUE TITLE
Hadron/Parton Flavor

### ISSUE THREAD

**Issue by jpazzini** [CMS-PD/ALPHA#185]
To apply btag correctly the flavour information should be provided to the BtagCorrectorr Tool.
Please add both the new one (HadronFlavor) and the old one (PartonFlavor) for reference.

(Currently the PartonFlavour is passed to the 'flavor' Jet variable)

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideBTagMCTools#Hadron_parton_based_jet_flavour

**Comment by MDallOsso** [comment]
done in 
https://github.com/CMS-PD/ALPHA/blob/master/plugins/JetAnalyzer.cc#L698
for reshaping with iterativefit.

martino
