### ISSUE TITLE
about JES/JER syst

### ISSUE THREAD

**Issue by MDallOsso** [CMS-PD/ALPHA#188]
to apply JES/JER up/Down variations to the HH analysis 
we currently select one shift (e.g. JES up) in the config file 
and then we run the entire analysis flow using jet with JESup correction applied. 
this is done before any jets selection.

What is the approach of the other analysis?
If it is equivalent we can add an option in the JetAnalyzer to chose which correction needs to be applied.
However, this means that you have to run alpha code 5 times per each sample on which you need to compute jes/jer effect (we have just signal).

Let's continue the discussion here in this github issue.
Martino

p.s. does the 'JERUncertaintyUp' have to be applied instead of the nominal 'JERUncertainty' or it has to be added to the previously corrected pt?

**Comment by MDallOsso** [comment]
Additional issue:
- new JEC SF are stored in different files for data, accordingly to Run.
https://twiki.cern.ch/twiki/bin/view/CMS/JECDataMC#Jet_Energy_Corrections_in_Run2

further coding is needed to implement it (how can I get run info at config level?)

**Comment by MDallOsso** [comment]
first implementation here:
https://github.com/cms-hh-pd/ALPHA/tree/jet_syst

to do list:
- [jec shift] need to implement selection of jec shift up/down in jetanalyzer.cc 
- [data txt] run dependent selection of the jec.txt files to be implemented in script/jetanalyzer
- [file name] think about convention for file names in order to distinguish up/down output from nominal one.

**Comment by MDallOsso** [comment]
partially solved with #193
to do list:
    - [jec shift] need to implement selection of jec shift up/down in jetanalyzer.cc
    - [file name] think about convention for file names in order to distinguish up/down output from nominal one.

**Comment by MDallOsso** [comment]
which is the idea behind this?
https://github.com/CMS-PD/ALPHA/blame/master/plugins/JetAnalyzer.cc#L265

to save different jet variables for up, down, central correction and to select them later on?
The HH approach was instead to re-run the entire event selection for each of the three options. 
This leads to 3 output files per MC sample.

my proposal is to add an option in the config file in order to select which correction to apply in the file:
- whichJER = 
   -1  -> JERdown
   0   -> JER
   +1 -> JERup
   3 -> three jet branch saved
the same can be done for JEC.
what do you think?

**Comment by lbenato** [comment]
JER-JES issues fixed.
