### ISSUE TITLE
Wrong c_nEvents for ST_s-channel

### ISSUE THREAD

**Issue by MDallOsso** [CMS-PD/ALPHA#240]
This is a general WARNING about the sample
ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1-v1

there is a mismatch between the generated number of events written in DAS and the one computed with counterAnalyzer:
n_ev in DAS: 1000000
n_ev in c_nEvents:  622990

The sample processed with ALPHS actually has 999975 events 
so I guess the DAS number is the correct one.
I do not think we can do much to that. 
Just keep in mind this in order to compute weight for this sample.

Martino

**Comment by lbenato** [comment]
Hi, actually the right number is that in c_nEvents.
DAS reports the number of total GENERATED events, but you need to take into account negative weights of NLO samples. So, the number of events to consider for the normalization is computed properly by CounterAnalyzer and is reported in c_nEvents.

**Comment by MDallOsso** [comment]
Okay, thank you very much for the clarification.

Martino
